version: "3.3"
services:
  news_echarts:
    restart: always
    image: news_echarts:v1
    build: ../
    volumes:
      - ../src:/app
    links:
      - redis
      - mysql
    environment:
      STAGE: development
    command: sleep 999999999

  redis:
    image: redis:alpine
    restart: always

  news_echarts_nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "news_echarts"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: news_echarts
      MYSQL_PASSWORD: 123456
    restart: always
